// Generated by tools/generate-model-catalog-runtime-mirror.js from packages/model-catalog/src/models.ts. Do not edit by hand.

export const catalogVersion = "saphnexa-model-catalog-2026-05-27";

export const modelIds = [
  "logical-chat-default",
  "logical-evaluation-judge",
  "logical-embedding-default"
];

export const llmModels = [
  {
    tenant_id: "global",
    model_id: "logical-chat-default",
    display_name: "Saphnexa Chat Default",
    provider: "bedrock",
    model_type: "chat",
    capability_json: { streaming: true, tool_use: true, max_context_tokens: 200000 },
    status: "active",
    visible_to_user: true,
    allowed_role: "general_user",
    default_for_task: "chat_default",
    catalog_version: catalogVersion
  },
  {
    tenant_id: "global",
    model_id: "logical-evaluation-judge",
    display_name: "Saphnexa Evaluation Judge",
    provider: "bedrock",
    model_type: "judge",
    capability_json: { structured_output: true, max_context_tokens: 200000 },
    status: "active",
    visible_to_user: false,
    allowed_role: "admin",
    default_for_task: "evaluation_judge_default",
    catalog_version: catalogVersion
  },
  {
    tenant_id: "global",
    model_id: "logical-embedding-default",
    display_name: "Saphnexa Embedding Default",
    provider: "bedrock",
    model_type: "embedding",
    capability_json: { dimensions: 1024 },
    status: "active",
    visible_to_user: false,
    allowed_role: "system",
    default_for_task: "embedding_default",
    catalog_version: catalogVersion
  }
];
