// Generated by tools/generate-api-openapi-runtime-mirror.js from apps/api/src/middleware/csrf.ts. Do not edit by hand.

import { createErrorResponse } from "../../../../packages/domain/src/index.js";
import { publicApiRoutes } from "../../../../packages/api-contract/src/routes.js";
const csrfRequiredPaths = new Set(publicApiRoutes
    .filter((route) => route.csrfRequired)
    .map((route) => `${route.method} ${route.internalPath.replace(/\{[^}]+\}/g, "[^/]+")}`));
export function csrfBoundaryMiddleware() {
    return async (context, next) => {
        const method = context.req.method.toUpperCase();
        const pathname = new URL(context.req.url).pathname;
        const requiresCsrf = [...csrfRequiredPaths].some((pattern) => new RegExp(`^${pattern.replace(`${method} `, "")}$`).test(pathname));
        if (requiresCsrf && !context.req.header("x-csrf-token")) {
            return context.json(createErrorResponse("CSRF_TOKEN_MISSING", "CSRF token is required"), 403);
        }
        await next();
    };
}
