// Generated by tools/generate-api-openapi-runtime-mirror.js from apps/api/src/middleware/error.ts. Do not edit by hand.

import { createErrorResponse } from "@saphnexa/domain";
export function errorMiddleware() {
    return async (context, next) => {
        try {
            await next();
        }
        catch (error) {
            const failure = error instanceof Error ? error : new Error("Unexpected API failure");
            return context.json(createErrorResponse("INTERNAL_ERROR", failure.message), 500);
        }
    };
}
