// Generated by tools/generate-api-openapi-runtime-mirror.js from apps/api/src/middleware/origin.ts. Do not edit by hand.

import { createErrorResponse } from "@saphnexa/domain";
export function originMiddleware(options = {}) {
    return async (context, next) => {
        const origin = context.req.header("origin");
        if (origin && options.allowedOrigins?.length && !options.allowedOrigins.includes(origin)) {
            return context.json(createErrorResponse("ORIGIN_NOT_ALLOWED", "Origin is not allowed", { origin }), 403);
        }
        await next();
    };
}
