// Generated by tools/generate-api-openapi-runtime-mirror.js from apps/api/src/middleware/request-log.ts. Do not edit by hand.

export function requestLogMiddleware() {
    return async (context, next) => {
        const traceId = context.req.header("x-amzn-trace-id") ?? crypto.randomUUID();
        context.header("x-saphnexa-trace-id", traceId);
        await next();
    };
}
