// Generated by tools/generate-api-openapi-runtime-mirror.js from apps/api/src/middleware/session.ts. Do not edit by hand.

export function sessionMiddleware(options = {}) {
    const actorHeaderName = options.actorHeaderName ?? "x-saphnexa-actor-id";
    return async (context, next) => {
        const actorId = context.req.header(actorHeaderName);
        if (actorId)
            context.header("x-saphnexa-session-actor", actorId);
        await next();
    };
}
